apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-app
        image: gcr.io/[PROJECT_ID]/streamlit-app:v1 
        ports:
        - containerPort: 8501
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri
              key: MONGO_URI
